### ISSUE TITLE
Installing via NPM [LINUX][NODE 5.6.0][NPM 3.6.0]

### ISSUE THREAD

**Issue by WebDevBren** [Icenium/icenium-cli#1414] opened 2016-05-24 15:24 UTC
when installing i get this error : 

    > fibers@1.0.6 install   /home/sysadmin/.nvm/versions/node/v5.6.0/lib/node_modules/appbuilder/node_modules/fibers
    > node build.js || nodejs build.js

    module.js:440
        throw err;
        ^

    Error: Cannot find module '    /home/sysadmin/.nvm/versions/node/v5.6.0/lib/node_modules/appbuilder/node_modules/fibers/build.js'
        at Function.Module._resolveFilename (module.js:438:15)
        at Function.Module._load (module.js:386:25)
        at Function.Module.runMain (module.js:575:10)
        at startup (node.js:160:18)
        at node.js:445:3
    module.js:440
        throw err;
        ^

    Error: Cannot find module   '/home/sysadmin/.nvm/versions/node/v5.6.0/lib/node_modules/appbuilder/node_modules/fibers/build.js     '
        at Function.Module._resolveFilename (module.js:438:15)
        at Function.Module._load (module.js:386:25)
        at Function.Module.runMain (module.js:575:10)
        at startup (node.js:160:18)
        at node.js:445:3
    /home/sysadmin/.nvm/versions/node/v5.6.0/lib

Now i've checked and i have seen https://github.com/iron-meteor/iron-cli/issues/207
where fibers version 1.0.6 does not exist. 

i have included the debug log. 
[npm-debug.log.txt](https://github.com/Icenium/icenium-cli/files/279836/npm-debug.log.txt)

**Comment by stephen-nba** [comment] 2016-07-19 01:42
I get the same error, Windows 7, Node v6.2.2, NPM v3.9.5
```

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "appbuilder"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.6 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.6 install script 'node build.js || nodejs buil
d.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Temp\src\appbuilder\npm-debug.log


```
[npm-debug.log.txt](https://github.com/Icenium/icenium-cli/files/370490/npm-debug.log.txt)

**Comment by rosen-vladimirov** [comment] 2016-07-19 05:42
@stephen-nba support for Node.js 6.x.x will be included  in our next official release. At the moment I recommend you to use LTS version of Node.js 4.x.x.
@WebDevBren can you try cleaning your cache (`npm cache clean`) and installing appbuilder again?

**Comment by stephen-nba** [comment] 2016-07-19 05:46
Yep i've uninstalled v6 and installed v5 and it worked ok.

**Comment by rosen-vladimirov** [comment] 2016-09-21 13:01
I'm closing this thread as the issue is resolved now.

**Closed by rosen-vladimirov** 2016-09-21 13:01 UTC
